# Generated by Django 6.0.5 on 2026-06-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(fields=('professional', 'date'), name='unique_professional_date'),
        ),
    ]
