# Generated by Django 6.0.5 on 2026-06-04 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('social_name', models.CharField(max_length=255, verbose_name='Nome Social')),
                ('profession', models.CharField(choices=[('MEDICINE', 'Medicine'), ('PSYCHOLOGY', 'Psychology'), ('NURSING', 'Nursing'), ('NUTRITION', 'Nutrition'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('SOCIAL_SERVICE', 'Social Service'), ('DENTISTRY', 'Dentistry'), ('OTHER', 'Other')], verbose_name='Profissão')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
                'ordering': ['social_name'],
            },
        ),
    ]
